rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('index/', views.index, name='index'), # 这个是自己加的，因为比较符合书写和思维习惯
    path('about/', views.about, name = 'about'),
    path('category/<slug:category_name_slug>/',
         views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),# 书7.2章中加入
    path('category/<slug:category_name_slug>/add_page/',
         views.add_page, name='add_page'), # 书第7章课后练习中加入
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name = 'index'),
    path('rango/', include('rango.urls')), #将以rango/开头的url交给rango应用处理
    path('teacherChat/', include('teacherChat.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacherChat/urls.py
from django.urls import path
from teacherChat import views

app_name = 'teacherChat'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('goods/', views.goods_list, name='goods_list'),
]

rango/models.py
from django.db import models
# 书5.3章创建category和page两个模型
from django.template.defaultfilters import slugify


class Category(models.Model):
    Name_MAX_LENGTH = 128 # 书第7章课后练习中要求加入该变量
    name = models.CharField(max_length=Name_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    # 书6.3章中加入，使得分类的别名无法重复，对别名为空的分类会有影响
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    TITLE_MAX_LENGTH = 128 # 书第7章课后练习中要求加入该变量
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

teacherChat/models.py
from django.db import models

class Goods(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField()

    def __str__(self):
        return self.name

rango/forms.py
# 书7.2章中加入
from django import forms
from rango.models import Page, Category
# We could add these forms to views.py, but it makes sense to split them off into their own file.

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.Name_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False) # 该字段也被隐藏，且指明该字段不是必须的。这里没有设置初始值，
    # 因为我们之前在admin中设定过slug字段可以自动生成。

    class Meta:
        model = Category
        fields = ('name',) # fields指定表单中包括哪些字段，也就是用户可见的


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0) # 这里的小组件是将该字段设为隐藏值，用户无法输入，但是设置了初始值

    class Meta:
        model = Page
        exclude = ('category',) # exclude指定表单中排除哪些字段，也就是用户不可见的

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse

from rango.forms import CategoryForm, PageForm
from rango.models import Category # 第6.2章加入 导入Category模型
from rango.models import Page# 第6.3章加入 导入Page模型

def index(request):
    # 书4.1和4.2加入
    # context_dict = {'boldmessage': "Crunchy, creamy, cookie, candy, cupcake!"}
    # return render(request, 'rango/index.html', context=context_dict)

    # 书6.2加入
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    # Spoiler: you don't need to pass a context dictionary here.
    # 书第四章课后练习
    return render(request, 'rango/about.html', {})

# 第6.3章加入
def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request,'rango/category.html',context=context_dict)

# 书7.2章加入
def add_category(request):
    form = CategoryForm()

    # 是http的post请求吗？
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})
    # 注意，这部分代码里没有context_dict变量，其实只是省略了，render函数中的最后一个参数其实就是

# 书第7章课后练习中加入
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    # You cannot add a page to a Category that does not exist... DM
    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)  # This could be better done; for the purposes of TwD, this is fine. DM.

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

teacherChat/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

from teacherChat.models import Goods


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('goods_list')
        else:
            return render(request, 'login.html', {'error': 'Invalid credentials'})
    return render(request, 'teacherChat/login.html')

@login_required
def goods_list(request):
    goods = Goods.objects.all()
    return render(request, 'teacherChat/goods_list.html', {'goods': goods})

templates/rango/about.html
<!--changed in 8 exercise-->
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	About Page
{% endblock %}

{% block body_block %}
	<h1>About says ... </h1>
	<div>
		here is the about page <br />
		This tutorial has been put together by Zheng Zhuang!<br />
	</div>
	<div>
		<img src="{% static 'images/about.jpg' %}" alt="Picture of About" />
		<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of About" />
	</div>
{% endblock %}

<!--<!DOCTYPE html>-->

<!--{% load staticfiles %} &lt;!&ndash; New line &ndash;&gt;-->

<!--<html>-->
<!--	<head>-->
<!--		<title>About</title>-->
<!--	</head>-->

<!--	<body>-->
<!--		<h1>About says ... </h1>-->
<!--		<div>-->
<!--			here is the about page <br />-->
<!--			This tutorial has been put together by Zheng Zhuang!<br />-->
<!--		</div>-->
<!--		<div>-->
<!--			<a href="/rango/index/"> A link to the index page.</a><br />-->
<!--			<img src="{% static 'images/about.jpg' %}" alt="Picture of About" />-->
<!--			<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of About" />-->
<!--		</div>-->
<!--	</body>-->
<!--</html>-->

templates/rango/add_category.html
<!--changed in 8 exercise-->
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
        <h1>Add a Category</h1>
        <div>
            <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category" />
            </form>
        </div>
{% endblock %}

<!--&lt;!&ndash;			书第7.1章加入&ndash;&gt;-->
<!--<!DOCTYPE html>-->

<!--<html>-->
<!--    <head>-->
<!--        <title>Rango</title>-->
<!--    </head>-->

<!--    <body>-->
<!--        <h1>Add a Category</h1>-->
<!--        <div>-->
<!--            <form id="category_form" method="post" action="/rango/add_category/">-->
<!--                {% csrf_token %}-->
<!--                {% for hidden in form.hidden_fields %}-->
<!--                    {{ hidden }}-->
<!--                {% endfor %}-->
<!--                {% for field in form.visible_fields %}-->
<!--                    {{ field.errors }}-->
<!--                    {{ field.help_text }}-->
<!--                    {{ field }}-->
<!--                {% endfor %}-->
<!--                <input type="submit" name="submit" value="Create Category" />-->
<!--            </form>-->
<!--        </div>-->
<!--    </body>-->
<!--</html>-->

templates/rango/add_page.html
<!--changed in 8 exercise-->
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add a Page
{% endblock %}

{% block body_block %}
<h1>Add a Page to {{ category.name }}</h1>
        <div>
            <form id="add_page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
                {% csrf_token %}
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}<br />
                {% endfor %}
                <input type="submit" name="submit" value="Add Page" />
            </form>
        </div>
{% endblock %}


<!--&lt;!&ndash;			书第7章课后练习中要求加入&ndash;&gt;-->
<!--<!DOCTYPE html>-->

<!--<html>-->
<!--    <head>-->
<!--        <title>Rango</title>-->
<!--    </head>-->

<!--    <body>-->
<!--        <h1>Add a Page to {{ category.name }}</h1>-->
<!--        <div>-->
<!--            <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">-->
<!--                {% csrf_token %}-->
<!--                {% csrf_token %}-->
<!--                {% for hidden in form.hidden_fields %}-->
<!--                    {{ hidden }}-->
<!--                {% endfor %}-->
<!--                {% for field in form.visible_fields %}-->
<!--                    {{ field.errors }}-->
<!--                    {{ field.help_text }}-->
<!--                    {{ field }}<br />-->
<!--                {% endfor %}-->
<!--                <input type="submit" name="submit" value="Add Page" />-->
<!--            </form>-->
<!--        </div>-->
<!--    </body>-->
<!--</html>-->

templates/rango/base.html
<!--changed in 8.2-->
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}<!--加载了这个标签才可以使用侧边栏-->

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <hr />
        <div> <!-- Sidebar block added. DM -->
            {% block sidebar_block %}
                {% get_category_list category %}<!--get_category_list是方法，category是参数-->
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
        {% else %}
        <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/rango/category.html
<!--changed in 8.3-->
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}

    <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}


<!--<!DOCTYPE html>-->

<!--<html>-->
<!--	<head>-->
<!--		<title>Rango</title>-->
<!--	</head>-->
<!--	<body>-->
<!--		<div>-->
<!--            {% if category %}-->
<!--			<h1>{{ category.name }}</h1>-->
<!--				{% if pages %}-->
<!--			<ul>-->
<!--				{% for page in pages %}-->
<!--				<li><a href="{{ page.url }}">{{ page.title }}</a></li>-->
<!--				{% endfor %}-->
<!--			</ul>-->
<!--				{% else %}-->
<!--			<strong>No pages currently in category.</strong><br />-->
<!--				{% endif %}-->

<!--&lt;!&ndash;			书第7章课后练习中要求加入&ndash;&gt;-->
<!--			<a href="/rango/category/{{ category.slug }}/add_page/">Add a Page.</a><br />-->
<!--			{% else %}-->
<!--			The specified category does not exist.-->
<!--			{% endif %}-->
<!--        </div>-->

<!--		<a href="/rango/index/">Go back to the index page.</a>-->
<!--	</body>-->
<!--</html>-->

templates/rango/index.html
<!--changed in 8 exercise-->
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Homepage
{% endblock %}

{% block body_block %}
	<h1>Rango says ... </h1>
		<div>
			hey there partner! <br />
			<strong>{{ boldmessage }}</strong><br />
		</div>

		<div>
			<h2>Most Liked Categories</h2>
			{% if categories %}
			<ul>
				{% for category in categories %}
				<li>
					<a href="{% url 'rango:show_category' category.slug %}"> {{ category.name }}</a><!--changed in 8.1-->
				</li>
				{% endfor %}
			</ul>
			{% else %}
			<strong>There are no categories present.</strong>
			{% endif %}
		</div>

		<div>
			<h2>Most Viewed Pages</h2>
			{% if pages %}
			<ul>
				{% for page in pages %}
				<li>
					<a href="{{ page.url }}">{{ page.title }}</a>
				</li>
				{% endfor %}
			</ul>
			{% else %}
			<strong>There are no pages present.</strong>
			{% endif %}
		</div>

		<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
{% endblock %}

<!--<!DOCTYPE html>-->

<!--{% load staticfiles %} &lt;!&ndash; New line &ndash;&gt;-->

<!--<html>-->
<!--	<head>-->
<!--		<title>Rango</title>-->
<!--	</head>-->

<!--	<body>-->
<!--		<h1>Rango says ... </h1>-->
<!--		<div>-->
<!--			hey there partner! <br />-->
<!--			<strong>{{ boldmessage }}</strong><br />-->
<!--		</div>-->

<!--		<div>-->
<!--			<h2>Most Liked Categories</h2>-->
<!--			{% if categories %}-->
<!--			<ul>-->
<!--				{% for category in categories %}-->
<!--				<li>-->
<!--					<a href="{% url 'rango:show_category' category.slug %}"> {{ category.name }}</a>&lt;!&ndash;changed in 8.1&ndash;&gt;-->
<!--				</li>-->
<!--				{% endfor %}-->
<!--			</ul>-->
<!--			{% else %}-->
<!--			<strong>There are no categories present.</strong>-->
<!--			{% endif %}-->
<!--		</div>-->

<!--		<div>-->
<!--			<h2>Most Viewed Pages</h2>-->
<!--			{% if pages %}-->
<!--			<ul>-->
<!--				{% for page in pages %}-->
<!--				<li>-->
<!--					<a href="{{ page.url }}">{{ page.title }}</a>-->
<!--				</li>-->
<!--				{% endfor %}-->
<!--			</ul>-->
<!--			{% else %}-->
<!--			<strong>There are no pages present.</strong>-->
<!--			{% endif %}-->
<!--		</div>-->

<!--		<div>-->
<!--			<a href="{% url 'rango:about' %}">A link to the about page.</a><br />&lt;!&ndash;changed in 8.1&ndash;&gt;-->
<!--			<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />-->
<!--		</div>-->

<!--		<div>-->
<!--			<a href="/rango/add_category/">Add a New Category.</a><br />-->
<!--		</div>-->
<!--	</body>-->
<!--</html>-->

templates/teacherChat/goods_list.html
<!-- goods_list.html -->
<h1>Goods List</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        {% for goods in goods %}
        <tr>
            <td>{{ goods.name }}</td>
            <td>{{ goods.category }}</td>
            <td>{{ goods.price }}</td>
            <td>{{ goods.description }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/teacherChat/login.html
<!-- login.html -->
<h1>Login</h1>
{% if error %}
<p style="color: red">{{ error }}</p>
{% endif %}
<form method="post">
    {% csrf_token %}
    <p>
        <label for="username">Username:</label>
        <input type="text" name="username" id="username">
    </p>
    <p>
        <label for="password">Password:</label>
        <input type="password" name="password" id="password">
    </p>
    <button type="submit">Login</button>
</form>